import os
from dotenv import load_dotenv

load_dotenv()


def _env(key: str, default: str = "") -> str:
    # Remove BOM (U+FEFF) e espaços que o PowerShell pode injetar via CLI
    val = os.getenv(key, default)
    return val.lstrip("﻿").strip() if val else default


DISCORD_WEBHOOK_URL = _env("DISCORD_WEBHOOK_URL")
DISCORD_WEBHOOK_DESIGNER   = _env("DISCORD_WEBHOOK_DESIGNER")
DISCORD_WEBHOOK_DESIGNER_2 = _env("DISCORD_WEBHOOK_DESIGNER_2")
DISCORD_WEBHOOK_CXCS = _env("DISCORD_WEBHOOK_CXCS")
DISCORD_WEBHOOK_AUTOMACAO = _env("DISCORD_WEBHOOK_AUTOMACAO")
DISCORD_WEBHOOK_DEV   = _env("DISCORD_WEBHOOK_DEV")
DISCORD_WEBHOOK_EDFIS = _env("DISCORD_WEBHOOK_EDFIS")
DISCORD_WEBHOOK_CRM   = _env("DISCORD_WEBHOOK_CRM")
DISCORD_WEBHOOK_DATA  = _env("DISCORD_WEBHOOK_DATA")
DISCORD_WEBHOOK_POPM  = _env("DISCORD_WEBHOOK_POPM")
DISCORD_WEBHOOK_QA    = _env("DISCORD_WEBHOOK_QA")

# Upstash Redis (deduplicação — substitui SQLite no serverless)
UPSTASH_REDIS_REST_URL = _env("UPSTASH_REDIS_REST_URL")
UPSTASH_REDIS_REST_TOKEN = _env("UPSTASH_REDIS_REST_TOKEN")

# Fallback local: SQLite (usado quando não há Redis configurado)
DB_PATH = os.getenv("DB_PATH", "vagas.db")

# Palavras-chave por categoria — filtro aplicado no título + descrição
KEYWORDS = {
    "automacao_presencial": [
        # Cargos
        "engenheiro de automação", "engenheiro de automacao",
        "engenheiro de automação industrial", "engenheiro automação industrial",
        "engenheiro de controle e automação", "engenheiro de controle e automacao",
        "engenheiro eletricista", "engenheiro elétrico", "engenheiro eletrico",
        "engenheiro mecatrônico", "engenheiro mecatronico",
        "técnico de automação", "tecnico de automacao",
        "analista de automação", "analista de automacao",
        "analista de instrumentação", "analista de instrumentacao",
        "supervisor de automação", "supervisor de automacao",
        "especialista em automação", "especialista em automacao",
        # Tecnologias
        "programador clp", "programador plc",
        "desenvolvedor clp", "desenvolvedor plc",
        "automação industrial", "automacao industrial",
        "controle e automação", "controle e automacao",
        "instrumentação industrial", "instrumentacao industrial",
        "instrumentação e controle",
        "SCADA", "CLP", "PLC", "DCS", "HMI",
        "Siemens TIA Portal", "Allen Bradley", "Rockwell",
        "STEP 7", "WinCC", "FactoryTalk",
        "commissioning automação", "startup automação",
        "redes industriais", "fieldbus", "profibus", "profinet",
        "IEC 61131",
    ],
    "automacao_remote": [
        # Cargos
        "projetista de automação", "projetista de automacao",
        "projetista elétrico", "projetista eletrico",
        "projetista de painéis", "projetista de paineis",
        "projetista industrial",
        "projetista mecânico", "projetista mecanico",
        "projetista hidráulico", "projetista hidraulico",
        "projetista CAD",
        "projetista de sistemas elétricos",
        "projetista sênior", "projetista pleno", "projetista junior",
        "engenheiro projetista",
        "analista projetista",
        # Ferramentas / disciplinas
        "EPLAN", "AutoCAD Electrical",
        "projetos elétricos industriais", "projetos de automação",
        "dimensionamento elétrico",
        "quadros elétricos", "painéis elétricos", "paineis eletricos",
        "diagramas elétricos", "diagramas unifilares",
        "SolidWorks Electrical",
        "memorial descritivo elétrico",
        "lista de materiais elétricos",
    ],
    "crm": [
        # IA + Lifecycle + CX + MarTech
        "forward deployed engineer",
        "fde ai martech",
        "ai agent architect",
        "ai agent product manager",
        "ai solutions architect crm",
        "desenvolvedor de agentes de ia",
        "engenheiro de integracao de agentes",
        "especialista em crm e inteligencia artificial",
        "ai lifecycle marketing",
        "crm preditivo",
        "predictive crm specialist",
        "ai-driven growth specialist",
        "analista de dados de crm machine learning",
        "real-time personalization specialist",
        "ia conversacional",
        "conversational ai specialist",
        "prompt engineer crm",
        "prompt engineer cx",
        "conversational ai product owner",
        "automacao de atendimento ia generativa",
        "arquiteto de bots agentes autonomos",
        "ai martech operations specialist",
        "cdp ai data specialist",
        "orquestracao de agentes crm",
        "engenheiro de dados de consumidor ia",
        "head of ai customer experience",
        "head of ai-driven crm",
        "tech lead agentes de ia",
        "gerente de agentes de ia",
        "lifecycle marketing specialist",
        "lifecycle marketing manager",
        "retention marketing specialist",
        "retention marketing manager",
        "especialista em engajamento e reativacao",
        "especialista de prevencao a churn",
        "churn specialist",
        "customer marketing specialist",
        "customer marketing manager",
        "monetizacao de base",
        "marketing automation specialist",
        "marketing automation architect",
        "especialista de martech",
        "analista de martech",
        "marketing operations analyst",
        "marketing operations manager",
        "marketing ops",
        "arquiteto de solucoes de marketing",
        "growth marketing manager",
        "growth marketing specialist",
        "retention growth manager",
        "ltv specialist",
        "ltv manager",
        "product growth analyst",
        "especialista em canais proprietarios",
        "owned media specialist",
        "inbound marketing specialist",
        "inbound marketing manager",
        "messaging push notification specialist",
        "email marketing manager",
        "analista de mensageria whatsapp",
        "loyalty specialist",
        "loyalty manager",
        "especialista em programas de fidelidade",
        "gerente de programas de fidelidade",
        "customer journey specialist",
        "customer journey manager",
        "especialista de mapeamento de jornada",
        "customer experience specialist",
        "customer experience manager",
        "analista de voc voice of customer",
        "analista de nps",
        "cdp specialist",
        "customer data platform specialist",
        "customer data analyst",
        "customer intelligence specialist",
        "database marketing analyst",
        "analista de segmentacao consumidor",
        "martech data specialist",
        "product manager martech",
        "product manager lifecycle",
        "product manager growth",
        "product owner plataformas de marketing",
        "analista de crm marketing",
        "analista de marketing de relacionamento",
        "analista de regua de relacionamento",
        "analista de automacao de marketing",
        "analista de inbound marketing",
        "analista de lifecycle marketing",
        "analista de retencao e engajamento",
        "growth crm specialist",
        "retention specialist",
        "especialista em crm e ltv",
        "analista de crm data analytics",
        "analista de operacoes de crm",
        "crm ops",
        "especialista de growth e lifecycle",
        "especialista de canais digitais",
        "digital channels specialist",
        "analista de programas de fidelidade",
        "especialista em customer experience e crm",
        "analista de omnichannel",
        "coordenador de crm e growth",
        "coordenador de lifecycle marketing",
        "coordenador de marketing de relacionamento",
        "gerente de crm e martech",
        "gerente de lifecycle e retention",
        "head de crm e growth",
        "head de customer marketing",
        "head de lifecycle martech",
        "diretor de crm e customer experience",
        "crm lifecycle marketing manager",
        "customer retention specialist",
        "crm operations manager",
        "crm data analyst",
        "crm product owner",

        "crm", "aprendiz crm", "estagiario crm", "estágio crm",
        "assistente de crm", "assistente crm",
        "analista de crm", "analista crm",
        "analista de crm jr", "analista de crm junior", "analista de crm pleno",
        "analista de crm senior", "analista de crm sênior",
        "especialista de crm", "especialista em crm", "especialista crm",
        "coordenador de crm", "coordenador crm", "coordenadora de crm",
        "supervisor de crm", "supervisor crm",
        "gerente de crm", "gerente crm", "crm manager",
        "gestor de crm", "gestor crm",
        "diretor de crm", "diretor crm", "diretora de crm",
        "head de crm", "head crm", "head of crm",
        "vp de crm", "chief customer officer", "cco",
        "consultor de crm", "consultor crm",
        "crm analyst", "crm specialist", "crm coordinator",
        "crm strategist", "crm director", "crm lead", "crm consultant",
        "crm executive", "crm supervisor", "crm product owner",
        "crm marketing", "analista de crm marketing",
        "marketing de relacionamento", "analista de marketing de relacionamento",
        "régua de relacionamento", "regua de relacionamento",
        "analista de régua de relacionamento", "analista de regua de relacionamento",
        "estrategia de crm", "estratégia de crm",
        "estrategia de canais crm", "estratégia de canais crm",
        "canais de relacionamento", "canais digitais crm",
        "jornada de cliente", "jornadas de clientes", "jornada do cliente",
        "customer journey", "jornada do consumidor",
        "customer journey specialist", "customer journey manager",
        "lifecycle marketing", "marketing de ciclo de vida",
        "analista de lifecycle marketing", "lifecycle marketing specialist",
        "lifecycle marketing manager",
        "analista de retencao", "analista de retenção",
        "analista de retencao e engajamento", "analista de retenção e engajamento",
        "retention specialist", "retention marketing specialist",
        "retention marketing manager", "retention growth manager",
        "customer retention specialist",
        "especialista em engajamento", "especialista em reativacao",
        "especialista em reativação",
        "especialista de prevencao a churn", "especialista de prevenção a churn",
        "prevencao de churn", "prevenção de churn",
        "customer marketing specialist", "customer marketing manager",
        "monetizacao de base", "monetização de base",
        "automacao de marketing", "automação de marketing",
        "analista de automacao de marketing", "analista de automação de marketing",
        "marketing automation", "marketing automation specialist",
        "marketing automation manager", "marketing automation architect",
        "especialista em martech", "analista de martech",
        "martech specialist", "martech data specialist",
        "marketing operations", "marketing ops",
        "arquiteto de solucoes de marketing", "arquiteto de soluções de marketing",
        "inbound marketing", "analista de inbound marketing",
        "inbound marketing specialist", "inbound marketing manager",
        "email marketing", "analista de email marketing",
        "email marketing manager",
        "growth crm", "crm growth", "growth crm specialist",
        "especialista de crm growth", "especialista de growth e lifecycle",
        "growth marketing manager", "growth marketing specialist",
        "ltv specialist", "ltv manager", "crm e ltv",
        "product growth analyst", "analista de crm data",
        "crm data analyst", "crm data analytics",
        "analista de operacoes de crm", "analista de operações de crm",
        "crm ops", "crm operations manager",
        "canais digitais", "especialista de canais digitais",
        "analista de canais digitais", "digital channels specialist",
        "crm e canais",
        "programa de fidelidade", "especialista em programa de fidelidade",
        "loyalty specialist", "loyalty manager",
        "gerente de programa de fidelidade",
        "omnichannel", "analista de omnichannel",
        "customer experience e crm", "cx e crm",
        "customer experience specialist", "customer experience manager",
        "analista de voc", "voice of customer",
        "analista de nps", "customer success manager",
        "cdp specialist", "customer data platform",
        "customer data analyst", "customer intelligence specialist",
        "database marketing analyst", "database marketing",
        "analista de segmentacao", "analista de segmentação",
        "product manager martech", "product manager lifecycle",
        "product manager growth", "product owner martech",
        "forward deployed engineer", "fde",
        "forward deployed ai agent engineer",
        "ai agent architect", "desenvolvedor de agentes de ia",
        "ai solutions architect crm", "ai agent product manager",
        "especialista em crm e inteligencia artificial",
        "especialista em crm e inteligência artificial",
        "ai lifecycle marketing", "crm preditivo", "predictive crm",
        "ai-driven growth crm", "ia conversacional crm",
        "conversational ai crm", "prompt engineer crm",
        "automacao de atendimento crm", "automação de atendimento crm",
        "ai marketing ops", "orquestracao de agentes crm",
        "head of ai customer experience", "head of ai-driven crm",
        "salesforce",
        "estagiario salesforce", "assistente salesforce",
        "analista salesforce", "analista de salesforce",
        "analista funcional salesforce", "especialista salesforce",
        "consultor salesforce", "consultor de salesforce",
        "desenvolvedor salesforce", "developer salesforce",
        "administrador salesforce", "salesforce administrator", "salesforce admin",
        "salesforce developer", "salesforce consultant",
        "salesforce business analyst", "salesforce architect",
        "salesforce manager", "gerente salesforce",
        "marketing cloud", "sales cloud", "service cloud",
        "salesforce marketing cloud", "salesforce cpq",
        "salesforce data cloud", "agentforce",
        "salesforce marketing specialist",
        "hubspot",
        "analista de hubspot", "analista hubspot",
        "especialista hubspot", "hubspot specialist",
        "consultor hubspot", "hubspot consultant",
        "hubspot administrator", "hubspot admin",
        "desenvolvedor hubspot", "hubspot developer",
        "gerente hubspot", "hubspot manager",
        "hubspot marketing specialist",
        "rd station",
        "analista de rd station", "especialista rd station",
        "consultor rd station", "desenvolvedor rd station",
        "rd station marketing specialist",
        "dynamics crm", "microsoft dynamics crm",
        "pipedrive", "zoho crm",
        "active campaign", "activecampaign",
        "braze", "insider crm", "dinamize",
        "klaviyo", "oracle responsys",
        "analista de crm jr",
        "analista de crm pl",
        "analista de crm sr",
        "analista de crm marketing",
        "analista de marketing de relacionamento",
        "analista de regua de relacionamento",
        "analista de automacao de marketing",
        "analista de inbound marketing",
        "analista de email marketing",
        "analista de lifecycle marketing",
        "analista de ciclo de vida",
        "analista de retencao e engajamento",
        "growth crm specialist",
        "especialista de crm growth",
        "analista de retencao",
        "retention specialist",
        "especialista retencao",
        "especialista em crm e ltv",
        "especialista em crm martech",
        "analista de crm data",
        "analista de crm analytics",
        "analista de operacoes de crm",
        "crm ops",
        "especialista growth lifecycle",
        "analista de canais digitais",
        "digital channels specialist",
        "especialista de crm e canais",
        "crm push whatsapp sms",
        "analista de programas de fidelidade",
        "loyalty specialist",
        "fidelidade",
        "especialista em customer experience crm",
        "cx crm",
        "analista de omnichannel crm",
        "omnichannel",
        "coordenador de crm",
        "coordenadora de crm",
        "coordenador de crm growth",
        "coordenador lifecycle marketing",
        "coordenador de marketing de relacionamento",
        "coordenador fidelidade",
        "gerente de crm",
        "crm manager",
        "gerente crm",
        "gerente de crm martech",
        "gerente crm cx fidelizacao",
        "gerente de lifecycle retention",
        "gerente lifecycle",
        "head de crm",
        "head crm",
        "head of crm",
        "head de crm growth",
        "head crm growth",
        "head de customer marketing retention",
        "head de lifecycle martech",
        "diretor de crm",
        "diretora de crm",
        "director crm",
        "diretor de crm customer experience",
        "vp crm",
        "chief customer officer cco",
        "crm lifecycle marketing manager",
        "customer retention specialist",
        "marketing automation architect",
        "marketing automation specialist",
        "crm operations manager",
        "crm data analyst",
        "crm product owner",
        "salesforce marketing specialist",
        "hubspot marketing specialist",
        "rd station marketing specialist",
        "lifecycle marketing specialist",
        "lifecycle marketing manager",
        "retention marketing specialist",
        "especialista em engajamento reativacao",
        "especialista de prevencao a churn",
        "especialista retencao clientes",
        "customer marketing specialist",
        "customer marketing manager",
        "especialista em monetizacao de base",
        "upsell cross-sell",
        "marketing automation specialist",
        "marketing automation architect",
        "especialista martech",
        "analista martech",
        "marketing operations analyst",
        "marketing operations manager",
        "especialista ferramentas marketing salesforce",
        "hubspot braze rd station",
        "arquiteto de solucoes marketing",
        "especialista fluxos vendas nutricao",
        "growth marketing manager base",
        "growth marketing specialist base",
        "retention growth manager",
        "ltv specialist",
        "ltv manager",
        "product growth analyst onboarding ativacao",
        "especialista canais proprietarios",
        "owned media specialist",
        "inbound marketing specialist",
        "inbound marketing manager",
        "messaging push notification specialist",
        "email marketing manager",
        "copywriter conversao base",
        "analista mensageria whatsapp",
        "especialista mensageria in-app sms",
        "loyalty specialist",
        "loyalty manager",
        "gerente programas fidelidade recompensas",
        "especialista em parcerias e beneficios",
        "perks loyalty",
        "community manager",
        "especialista comunidades clientes",
        "customer journey specialist",
        "customer journey manager",
        "especialista mapeamento jornada cliente",
        "customer experience specialist",
        "customer experience manager",
        "cx",
        "analista voc voice of customer",
        "analista nps",
        "customer success manager csm",
        "csm onboarding retencao expansao",
        "cdp specialist",
        "customer data platform specialist",
        "customer data analyst",
        "customer intelligence specialist",
        "database marketing analyst",
        "analista segmentacao comportamento consumidor",
        "martech data specialist",
        "product manager martech",
        "pm martech lifecycle growth",
        "product owner plataformas marketing canais",
        "po marketing",
        "especialista solucoes cx martech",
        "ai agent architect",
        "ai agent product manager",
        "ai agent product specialist crm revops",
        "ai agent solutions architect",
        "ai agent success engineer",
        "ai lifecycle marketing manager specialist",
        "ai martech agent ops specialist",
        "ai martech cx",
        "ai martech operations specialist",
        "ai orchestration crm integration engineer",
        "ai solutions architect crm cx automation",
        "ai-driven growth specialist",
        "analista automacao atendimento ia generativa",
        "analista dados crm machine learning",
        "arquiteto automacao orquestracao agentes",
        "arquiteto bots agentes autonomos relacionamento",
        "arquiteto fluxos conversacionais automacao",
        "arquiteto solucoes agentes ia crm",
        "braze content specialist",
        "cdp ai data specialist",
        "consultor tecnico implantacao ia",
        "conversational ai product owner specialist",
        "conversational copywriter",
        "conversational experience designer",
        "copywriter de inbound e automacao",
        "copywriter de mensageria e conversao",
        "copywriter de revops",
        "copywriter inbound",
        "copywriter retencao nutricao base",
        "creative growth specialist",
        "creative operations specialist",
        "crm copywriter",
        "crm designer",
        "crm vendas",
        "cxd",
        "desenvolvedor agentes ia",
        "designer canais proprietarios push in-app whatsapp",
        "designer ciclo vida",
        "designer de automacao marketing",
        "designer de canais proprietarios",
        "designer email marketing",
        "designer experiencia conversacional",
        "designer fidelidade",
        "designer growth retencao",
        "designer plataformas automacao",
        "designer rd station braze insider one",
        "designer relacionamento",
        "designer ui jornadas clientes",
        "email marketing copywriter",
        "email marketing designer",
        "engenheiro automacao workflows agentes autonomos",
        "engenheiro campo ia generativa",
        "engenheiro dados consumidor modelos ia",
        "engenheiro especialista ia conversacional whatsapp",
        "engenheiro forward deployed agentes ia martech",
        "engenheiro implantacao agentes ia crm",
        "engenheiro integracao agentes crm salesforce hubspot",
        "engenheiro integracao agentes ia crm",
        "engenheiro solucoes ia conversacional jornadas",
        "especialista conteudo prompting ia",
        "especialista conteudo revops",
        "especialista conteudo visual hubspot rd station",
        "especialista criacao design regua relacionamento",
        "especialista criacao growth",
        "especialista criacao growth teste ab",
        "especialista criacao regua relacionamento",
        "especialista crm inteligencia artificial",
        "especialista crm preditivo",
        "especialista integracao llms tools conectores crm",
        "especialista operacoes criativas",
        "especialista orquestracao agentes crm",
        "especialista personalizacao tempo real",
        "fde",
        "forward deployed ai agent engineer",
        "forward deployed engineer",
        "forward deployed product manager",
        "forward deployed revops ia",
        "gerente agentes ia inovacao",
        "gerente implantacao agentes",
        "growth copywriter",
        "growth designer",
        "growth writer",
        "head ai customer experience",
        "head ai forward deployment integrations",
        "head ai-driven crm growth",
        "insider content specialist",
        "lider engenharia aplicacao ia relacionamento",
        "lider tecnico entrega agentes",
        "lifecycle copywriter",
        "lifecycle designer",
        "marketing ops",
        "martech visual specialist",
        "microcopy specialist",
        "owned media",
        "pm agentes ia",
        "predictive crm specialist",
        "prompt engineer jornadas cx crm vendas",
        "real-time personalization ai",
        "redator ciclo vida",
        "redator conversacional bots",
        "redator crm",
        "redator crm marketing",
        "redator de ciclo de vida",
        "redator email marketing",
        "redator mensageria conversao whatsapp sms kommo",
        "redator para agentes de ia e bots",
        "redator revops cadencias vendas",
        "revops creative specialist",
        "sales enablement",
        "tech lead agentes ia martech",
        "tech lead forward deployed ai",
        "technical onboarding specialist ai agents crm",
        "ui designer jornadas clientes",
        "ux writer",
        "ux writer jornadas cliente",
        "visual designer retencao",

        "crm copywriter",
        "lifecycle copywriter",
        "redator de ciclo de vida",
        "growth copywriter",
        "growth writer",
        "copywriter de inbound automacao",
        "copywriter de mensageria conversao",
        "copywriter de revops",
        "sales enablement",
        "conversational copywriter",
        "redator para agentes ia",
        "redator para bots",
        "email marketing copywriter",
        "ux writer",
        "microcopy specialist",
        "crm designer",
        "lifecycle designer",
        "growth designer",
        "designer automacao marketing",
        "email marketing designer",
        "designer canais proprietarios",
        "owned media",
        "visual designer retencao",
        "visual designer ltv",
        "martech visual specialist",
        "ui designer jornadas",
        "creative growth specialist",
        "especialista criacao growth",
        "conversational experience designer",
        "cxd",
        "especialista conteudo hubspot",
        "especialista conteudo rd station",
        "braze content specialist",
        "insider content specialist",
        "revops creative specialist",
        "creative operations specialist",
        "especialista criacao regua relacionamento",
        "forward deployed engineer",
        "fde",
        "ai martech",
        "forward deployed ai",
        "ai agent architect",
        "desenvolvedor agentes ia",
        "ai solutions architect",
        "ai solutions architect crm",
        "ai agent product manager",
        "engenheiro integracao agentes ia",
        "especialista crm inteligencia artificial",
        "ai lifecycle marketing manager",
        "ai lifecycle marketing specialist",
        "especialista crm preditivo",
        "predictive crm specialist",
        "ai-driven growth specialist",
        "analista dados crm machine learning",
        "especialista personalizacao tempo real",
        "ia conversacional",
        "engenheiro ia conversacional",
        "especialista ia conversacional",
        "prompt engineer",
        "prompt engineer crm",
        "prompt engineer vendas",
        "conversational ai product owner",
        "conversational ai specialist",
        "analista automacao atendimento ia",
        "arquiteto bots agentes autonomos",
        "ai martech operations specialist",
        "ai marketing ops",
        "cdp ai data specialist",
        "especialista orquestracao agentes crm",
        "engenheiro dados consumidor ia",
        "head ai customer experience",
        "head ai-driven crm growth",
        "tech lead agentes ia martech",
        "gerente agentes ia inovacao",
        "redator crm",
        "redator crm marketing",
        "copywriter retencao base",
        "copywriter inbound rd station",
        "redator mensageria whatsapp sms",
        "redator revops cadencias vendas",
        "redator email marketing",
        "designer ciclo vida",
        "designer email",
        "designer html css",
        "designer push notification",
        "designer in-app",
        "designer fidelidade",
        "redator conversacional",
        "designer experiencia conversacional",
        "especialista conteudo prompting ia",
        "arquiteto fluxos conversacionais",
        "especialista criacao teste ab",
        "especialista operacoes criativas",
        "forward deployed pm",
        "forward deployed product manager",
        "ai agent success engineer",
        "onboarding specialist ai agents",
        "lider tecnico entrega agentes",
        "head ai forward deployment",
        "lider engenharia aplicacao ia",
        "gerente implantacao agentes",
        "engenheiro automacao workflows agentes",
        "ai orchestration engineer",
        "especialista integracao llms tools",
        "arquiteto automacao agentes",
        "consultor tecnico implantacao ia",
        "engenheiro solucoes ia",
    
        "forward deployed engineer fde ai agents crm",
        "forward deployed ai agent engineer",
        "engenheiro forward deployed agentes ia martech",
        "forward deployed engineer revops ia conversacional",
        "engenheiro implantacao agentes ia crm",
        "engenheiro campo ia generativa vendas",
        "arquiteto solucoes agentes ia crm",
        "ai agent solutions architect cx",
        "arquiteto automacao orquestracao agentes",
        "consultor tecnico implantacao ia crm",
        "engenheiro solucoes ia conversacional jornadas",
        "engenheiro integracao agentes crm salesforce hubspot",
        "ai orchestration crm integration engineer",
        "especialista integracao llms tools conectores crm",
        "engenheiro automacao workflows agentes autonomos",
        "ai martech agent ops specialist",
        "forward deployed product manager pm agentes",
        "ai agent product specialist crm revops",
        "lider tecnico entrega agentes ia",
        "technical onboarding specialist ai agents crm",
        "ai agent success engineer",
        "tech lead forward deployed ai agents crm",
        "head ai forward deployment integrations",
        "lider engenharia aplicacao ia relacionamento",
        "gerente implantacao tecnica agentes ia",
            "agente ia",
        "agentes de ia",
        "forward deployed engineer ai agents crm",
        "forward deployed ai agent engineer",
        "engenheiro forward deployed agentes ia martech",
        "forward deployed engineer revops ia conversacional",
        "engenheiro implantacao agentes ia crm",
        "engenheiro campo ia generativa vendas",
        "arquiteto solucoes agentes ia crm",
        "ai agent solutions architect crm cx",
        "arquiteto automacao orquestracao agentes",
        "consultor tecnico implantacao ia crm",
        "engenheiro solucoes ia conversacional jornadas",
        "engenheiro integracao agentes crm salesforce",
        "engenheiro integracao agentes hubspot whatsapp",
        "ai orchestration crm integration engineer",
        "especialista integracao llms tools conectores",
        "engenheiro automacao workflows agentes autonomos",
        "ai martech agent ops specialist",
        "forward deployed product manager",
        "pm implantacao agentes",
        "ai agent product specialist crm revops",
        "lider tecnico entrega agentes ia",
        "technical onboarding specialist ai agents",
        "ai agent success engineer",
        "tech lead forward deployed ai agents crm",
        "head ai forward deployment integrations",
        "lider engenharia aplicacao ia relacionamento",
        "gerente implantacao tecnica agentes ia",

        "forward deployed engineer ai agents",
        "forward deployed ai agent engineer",
        "forward deployed agentes ia martech",
        "forward deployed engineer revops ia",
        "engenheiro implantacao agentes ia",
        "engenheiro campo ia generativa vendas",
        "arquiteto solucoes agentes ia",
        "ai agent solutions architect",
        "arquiteto automacao orquestracao agentes",
        "consultor tecnico implantacao ia",
        "engenheiro solucoes ia conversacional jornadas",
        "engenheiro integracao agentes ia salesforce hubspot",
        "ai orchestration integration engineer",
        "especialista integracao llms tools conectores",
        "engenheiro automacao workflows agentes",
        "ai martech agent ops specialist",
        "forward deployed product manager",
        "ai agent product specialist",
        "lider tecnico entrega agentes ia",
        "technical onboarding specialist ai agents",
        "ai agent success engineer",
        "tech lead forward deployed ai agents",
        "head ai forward deployment integrations",
        "lider engenharia aplicacao ia relacionamento",
        "gerente implantacao tecnica agentes ia",
        ],
    "data": [
        # Analista de dados
        "analista de dados", "analista dados", "data analyst",
        "analista de analytics", "analytics analyst",
        # Business Intelligence
        "analista de business intelligence", "analista de bi", "analista bi",
        "business intelligence analyst", "bi analyst",
        "analista power bi", "especialista power bi",
        "analista tableau", "especialista tableau",
        "power bi developer", "power bi engineer",
        # Cientista de dados
        "cientista de dados", "data scientist",
        "ciência de dados", "ciencia de dados",
        # Engenheiro de dados
        "engenheiro de dados", "engenheira de dados",
        "data engineer", "analytics engineer",
        "engenharia de dados",
        # Arquitetura / liderança de dados
        "arquiteto de dados", "arquiteta de dados", "data architect",
        "head de dados", "head of data", "gerente de dados",
        "líder de dados", "lider de dados",
        # Machine Learning / IA
        "machine learning engineer", "ml engineer",
        "engenheiro de machine learning", "engenheiro de ml",
        "ai engineer", "engenheiro de ia", "engenheiro de inteligência artificial",
        "mlops",
        # Ferramentas como cargo
        "analista dbt", "especialista dbt",
        "analista databricks", "engenheiro databricks",
        "analista snowflake",
        # Dados em geral
        "profissional de dados", "especialista em dados",
        "data steward", "data governance",
        "analista de dados jr", "analista de dados pleno", "analista de dados senior",
    ],
    "edfis": [
        # Cargo principal
        "educação física", "educacao fisica",
        "ed. física", "ed fisica",
        # Personal e Fitness
        "personal trainer",
        "instrutor de academia", "instrutor fitness",
        "instrutor de musculação", "instrutor de musculacao",
        "professor de musculação", "professor de musculacao",
        "treinador de musculação", "treinador de musculacao",
        # Preparação física
        "preparador físico", "preparador fisico",
        "preparação física", "preparacao fisica",
        # Modalidades
        "professor de natação", "professor de natacao",
        "instrutor de natação", "instrutor de natacao",
        "professor de pilates", "instrutor de pilates",
        "professor de yoga", "instrutor de yoga",
        "professor de crossfit", "instrutor de crossfit",
        "professor de dança", "professor de danca",
        "professor de artes marciais",
        "professor de futebol", "professor de volei", "professor de vôlei",
        # Coordenação / gestão esportiva
        "coordenador esportivo", "coordenador de esportes",
        "gestor esportivo", "supervisor esportivo",
        "professor de esportes",
        # Saúde corporativa / bem-estar
        "coordenador de bem-estar", "coordenador de wellness",
        "analista de saúde", "consultor de saúde",
    ],
    "po_pm": [
        # Product Owner
        "product owner", "po agile", "product owner jr", "product owner pleno",
        "product owner senior", "product owner sênior",
        "dono do produto", "dono de produto",
        # Product Manager
        "product manager", "gerente de produto", "gestora de produto",
        "gestor de produto", "gerente de produtos",
        "head of product", "head de produto", "head de produtos",
        "diretor de produto", "diretora de produto",
        "coordenador de produto", "coordenadora de produto",
        "líder de produto", "lider de produto",
        "product lead", "group product manager",
        # Product em geral (cargos com "produto" no título)
        "analista de produto", "analista de produtos",
        "especialista de produto", "especialista em produto",
        # Inglês
        "chief product officer", "cpo",
        "vp of product", "vp product",
        "senior product manager", "junior product manager",
        "associate product manager", "apm",
    ],
    "qa": [
        # QA em PT
        "analista de qualidade", "analista de testes", "analista de teste",
        "analista de qa", "analista qa",
        "engenheiro de qualidade", "engenheira de qualidade",
        "engenheiro de testes", "engenheira de testes",
        "especialista em qualidade", "especialista de qualidade",
        "especialista em testes", "especialista de testes",
        "coordenador de qualidade", "coordenadora de qualidade",
        "gerente de qualidade",
        "testador", "testadora",
        # QA em EN
        "quality analyst", "quality assurance", "quality engineer",
        "qa analyst", "qa engineer", "qa specialist", "qa lead",
        "qa manager", "qa automation", "qa manual",
        "test analyst", "test engineer", "test lead", "test manager",
        "tester", "software tester",
        # Automação de testes
        "automation tester", "automation qa",
        "sdet",
        "engenheiro de automação de testes",
        # Combinações comuns em BR
        "analista de testes funcionais", "analista de testes manuais",
        "analista de testes automatizados", "analista de automação de testes",
    ],
    "dev": [
        # Cargos PT
        "desenvolvedor", "desenvolvedora",
        "programador", "programadora",
        "engenheiro de software", "engenheira de software",
        # Cargos EN
        "developer", "software engineer", "software developer",
        # Especialidades
        "frontend", "front-end", "front end",
        "backend", "back-end", "back end",
        "fullstack", "full-stack", "full stack",
        "devops", "dev ops",
        "mobile developer", "web developer",
        "tech lead", "technical lead",
        # Liderança técnica e gestão de TI
        "gerente de tecnologia", "gerente de ti", "gerente de engenharia",
        "gerente de desenvolvimento", "gerente de software",
        "head de tecnologia", "head de ti", "head de engenharia",
        "head of engineering", "head of technology",
        "diretor de tecnologia", "diretor de ti", "diretor de engenharia",
        "diretor de desenvolvimento",
        "vp de engenharia", "vp de tecnologia",
        "vp of engineering", "vp engineering",
        "cto", "chief technology officer", "chief technical officer",
        "engineering manager", "engenheiro manager",
        "líder técnico", "lider tecnico",
        "líder de engenharia", "lider de engenharia",
        "coordenador de desenvolvimento", "coordenador de tecnologia",
        "coordenador de ti",
        # Linguagens/stacks como título (comum em job boards de TI)
        "flutter developer", "react developer", "node developer",
        "python developer", "java developer", "php developer",
    ],
    "designer": [
        # Cargos
        "designer", "designer gráfico", "designer grafico", "product designer",
        "ux designer", "ui designer", "web designer", "motion designer",
        "graphic designer", "visual designer", "design de produto",
        "designer de produto", "design gráfico", "design grafico",
        # Disciplinas / ferramentas
        "ux", "ui", "user experience", "user interface", "figma",
        "ilustração", "ilustracao", "illustrator", "branding",
        "identidade visual", "motion", "motion design", "visual design",
        "design system", "web design", "webdesign", "arte", "photoshop",
        "indesign", "prototipagem", "wireframe", "usabilidade",
        "acessibilidade", "accessibility", "criativo", "criativa",
        "ux/ui", "ui/ux",
    ],
    "cxcs": [
        # Cargos principais
        "customer success", "customer success manager", "csm",
        "sucesso do cliente", "sucesso de cliente",
        "cs jr", "cs pleno", "cs sr", "cs senior", "cs junior",
        "customer experience", "cx",
        "experiência do cliente", "experiencia do cliente",
        # Atendimento / suporte
        "atendimento ao cliente", "suporte ao cliente", "sac",
        "analista de atendimento", "assistente de atendimento",
        "analista de suporte", "assistente de suporte",
        "customer support", "support analyst",
        # Relacionamento
        "relacionamento com cliente", "relacionamento com o cliente",
        "analista de relacionamento", "gestão de relacionamento",
        "account manager", "key account",
        # Ciclo de vida
        "onboarding", "churn", "retenção", "retencao",
        "upsell", "cross-sell", "implementação", "implementacao",
        # Métricas / ferramentas
        "nps", "csat", "customer health", "customer journey",
        "voz do cliente", "voice of customer",
        # Help desk
        "help desk", "helpdesk", "service desk",
    ],
}

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
}

REQUEST_TIMEOUT = 8
REQUEST_DELAY = float(os.getenv("REQUEST_DELAY", "0"))  # 0 em serverless
